name: coinevo-core
version: 0.19.0
summary:   peer-to-peer network based digital currency
description: |
  Coinevo is a free open source peer-to-peer electronic cash system that
  is completely decentralized, without the need for a central server or
  trusted parties.  Users hold the crypto keys to their own money and
  transact directly with each other, with the help of a P2P network to
  check for double-spending.

grade: stable
confinement: strict

apps:
  daemon:
    command: evod
    plugs: [removable-media, network, network-bind]
    environment:
      # Override HOME so the datadir is located at
      # ~/snap/bitcoin-core/common/.bitcoin/ instead of
      # ~/snap/bitcoin-core/current/.bitcoin/, and each new version of the
      # snap won't have a different data directory:
      # https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: desktop-launch evo-qt
    plugs: [removable-media, network, network-bind, desktop, x11]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  cli:
    command: evo-cli
    plugs: [removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  coinevo-core:
    plugin: nil
    override-build: | 
      env | grep SNAP
      wget https://coinevo.tech/bin/coinevo-${SNAPCRAFT_PROJECT_VERSION}/SHA256SUMS.asc
      wget https://coinevo.tech/bin/coinevo-${SNAPCRAFT_PROJECT_VERSION}/coinevo-${SNAPCRAFT_PROJECT_VERSION}.tar.gz
      wget https://coinevo.tech/bin/coinevo-${SNAPCRAFT_PROJECT_VERSION}/coinevo-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      echo "03c5f9a2c9201729847c1ef0f8467d4401b69f0f2b12dd476edb871e98e458a5  SHA256SUMS.asc" | sha256sum --check
      sha256sum --ignore-missing --check SHA256SUMS.asc      
      tar -xvf coinevo-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      tar -xvf coinevo-${SNAPCRAFT_PROJECT_VERSION}.tar.gz
      echo "Running tests ..."
      -${SNAPCRAFT_PROJECT_VERSION}/bin/test_coinevo
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin coinevo-${SNAPCRAFT_PROJECT_VERSION}/bin/evod
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin coinevo-${SNAPCRAFT_PROJECT_VERSION}/bin/evo-qt
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin coinevo-${SNAPCRAFT_PROJECT_VERSION}/bin/evo-cli
      wget https://raw.githubusercontent.com/coinevo/evo/v${SNAPCRAFT_PROJECT_VERSION}/share/pixmaps/bitcoin128.png
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps bitcoin128.png
    build-packages:
      - wget
    after:
      - desktop-qt5
